### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coolpalani** [ifnoelse/kubernetes-deploy#2]
Could you make package downloads from internet instead of keep in local folder.
Also how do we change languages into english

**Comment by coolpalani** [comment]
I am still awaiting your updates.

**Comment by ifnoelse** [comment]
1. The speed is too slow to download some resources of kubernetes in china. So i put some files in the Baidu Net Disk. But you can also go to the offical to download the resources.
2. I will translate it into english later. I have been very busy with my work recently. Please give me some time.

**Comment by coolpalani** [comment]
Thank you very much for responding.
I am looking forward your English edition :)

**Comment by coolpalani** [comment]
Could you share kubernetes HA deployment where we can put 3 master node, 3 etcd , 2 worker node
or 3 master + 2 worker node.
