### ISSUE TITLE
K8s HA model

### ISSUE THREAD

**Issue by coolpalani** [ifnoelse/kubernetes-deploy#3]
Could you add Kubernetes HA features.

**Comment by ifnoelse** [comment]
They are already included Kubernetes HA features.

**Comment by ifnoelse** [comment]
I corrected an error in the document. The correct nodes description as follows：

| node name      | ip           |components.           |
| ------------- | ------------- |-------------|
| node-1      | 192.168.100.101 |haproxy，keepalived，kubernetes_master，kubernetes_client，flannel，etcd|
| node-2      | 192.168.100.102 |haproxy，keepalived，kubernetes_master，kubernetes_node，flannel，etcd，docker|
| node-3      | 192.168.100.103 |kubernetes_node，flannel，etcd，docker|

**Comment by coolpalani** [comment]
Thank you very much for responding. 👍 
I have added steps for manually configure Kubernetes cluster with 3 master node and 2 worker node.

https://github.com/coolpalani/k8s-kubeadm-ha

I will use ansible for deploy instead of manual and release it soon. :)

**Comment by ifnoelse** [comment]
:thumbsup: :thumbsup: :thumbsup: 

Sorry, I spent the Spring Festival at home a few days ago. So I didn't see your issue.

**Comment by coolpalani** [comment]
Well. Wishing you to commit more in Kubernetes

**Comment by ifnoelse** [comment]
Thanks for your advice and encouragement. ：)
